name: family_flow_app_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^7.0.0
  flow_builder: ^0.1.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  formz: ^0.8.0
  user_repository:
    path: packages/user_repository
  form_inputs:
    path: packages/form_inputs
  json_annotation: ^4.8.1
  shared_preferences: ^2.0.15
  family_repository:
    path: packages/family_repository
  family_api:
    path: packages/family_api
  todo_repository:
    path: packages/todo_repository
  todo_api:
    path: packages/todo_api
  shopping_repository:
    path: packages/shopping_repository
  shopping_api:
    path: packages/shopping_api
  wishlist_repository:
    path: packages/wishlist_repository
  wishlist_api:
    path: packages/wishlist_api
  intl: ^0.19.0
  table_calendar: ^3.0.9
  geolocator: ^14.0.0
  location: ^5.0.0
  yandex_mapkit: ^4.1.0
  permission_handler: ^12.0.0+1
  user_api:
    path: packages/user_api
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  notification_api:
    path: packages/notification_api
  notification_repository:
    path: packages/notification_repository
  flutter_local_notifications: ^19.1.0
  web_socket_channel: ^3.0.3
  chats_api:
    path: packages/chats_api
  chats_repository:
    path: packages/chats_repository
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  # geolocator_android: ^5.0.1+1
  diary_api:
   path: packages/diary_api
  diary_repository:
   path: packages/diary_repository
  emoji_picker_flutter: ^4.3.0
  timezone: ^0.10.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/user.png
