name: family_flow_app_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^9.0.0
  flow_builder: ^0.1.0
  equatable: ^2.0.0
  flutter_bloc: ^9.1.0
  formz: ^0.8.0
  user_repository:
    path: packages/user_repository
  form_inputs:
    path: packages/form_inputs
  json_annotation: ^4.8.1
  shared_preferences: ^2.0.15
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
