name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=1.17.0"
  
dependencies:
  equatable: ^2.0.0
  uuid: ^4.2.2
  shared_preferences: ^2.0.15
  http: ^1.3.0
  json_annotation: ^4.9.0
  user_api:
    path: ../user_api

dev_dependencies:
  json_serializable: ^6.0.0
  build_runner: ^2.0.0