name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"


dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
  shared_preferences: ^2.0.15
  http: ^1.3.0
  user_api:
    path: ../user_api
